name: xcitiman
favicon: null
layout_spectrum: 0.0897
typography_spectrum: 0.16228
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7670793600846082
  lightness: 0.984791808295995
  saturation: 0.22649347106926143
  rhythmicContrast: 0.8570382434409112
purpose: []
