name: xcitiman
favicon: null
layout_spectrum: 0.88762
typography_spectrum: 0.16228
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040000'
    - '#ff6d00'
    - '#be9a8b'
    - '#5f5e71'
    - '#efedee'
  brandStrength: 0.7670793600846082
  lightness: 0.984791808295995
  saturation: 0.875
  rhythmicContrast: 0.8570382434409112
purpose: []
